/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.RegistrarRole;

import Model.Registrar;
import UI.MainJFrame; 
import Model.ProfileManagementDialog; 
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

// Import all required feature panels
import UI.RegistrarRole.CourseOfferingJPanel;
import UI.RegistrarRole.StudentRegistrationJPanel;
import UI.RegistrarRole.FinancialReconciliationJPanel;
import UI.RegistrarRole.InstitutionalReportsJPanel;
/**
 *
 * @author jayan
 */
public class RegistrarDashboardJPanel extends javax.swing.JPanel {

    private MainJFrame mainFrame;
    private Registrar loggedInRegistrar;
    private CardLayout workAreaLayout;
    
    // Feature Panels (instantiated once)
    private CourseOfferingJPanel courseOfferingPanel;
    private StudentRegistrationJPanel studentRegistrationPanel;
    private FinancialReconciliationJPanel financialReportsPanel;
    private InstitutionalReportsJPanel institutionalReportsPanel;
    
    // Constructor must accept the MainFrame and the logged-in user object
    public RegistrarDashboardJPanel(MainJFrame mainFrame, Registrar registrar) {
        initComponents();
        this.mainFrame = mainFrame;
        this.loggedInRegistrar = registrar;
        
        // 1. Initialize CardLayout and Panels
        workAreaLayout = (CardLayout) workArea.getLayout();
        initializeWorkAreaPanels();
        
        // 2. Set Welcome Label Text
        updateWelcomeLabel();
    }
    
    private void updateWelcomeLabel() {
         lblWelcomeTitle.setText("Welcome, " + loggedInRegistrar.getPerson().getName().split(" ")[0] + "!");
    }
    
    // Helper method to instantiate all feature panels and add them to the CardLayout
    private void initializeWorkAreaPanels() {
        // Instantiate your feature panels (You must ensure these constructors are present)
        // In a complex app, you would pass DataStore/Services into these panels
        courseOfferingPanel = new CourseOfferingJPanel(); 
        studentRegistrationPanel = new StudentRegistrationJPanel();
        financialReportsPanel = new FinancialReconciliationJPanel();
        institutionalReportsPanel = new InstitutionalReportsJPanel();
        
        // Add panels to the CardLayout
        workArea.add(courseOfferingPanel, "CourseOffering");
        workArea.add(studentRegistrationPanel, "StudentRegistration");
        workArea.add(financialReportsPanel, "FinanceReports");
        workArea.add(institutionalReportsPanel, "InstitutionalReports");
        
        // Display the first panel by default
        workAreaLayout.show(workArea, "CourseOffering");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlArea = new javax.swing.JPanel();
        btnCourseOffering = new javax.swing.JButton();
        btnStudentRegistration = new javax.swing.JButton();
        btnFinanceReports = new javax.swing.JButton();
        btnInstitutionalReports = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        lblWelcomeTitle = new javax.swing.JLabel();
        workArea = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(755, 465));
        setMinimumSize(new java.awt.Dimension(755, 465));
        setPreferredSize(new java.awt.Dimension(755, 465));

        controlArea.setBackground(new java.awt.Color(255, 255, 204));
        controlArea.setMaximumSize(new java.awt.Dimension(155, 465));
        controlArea.setMinimumSize(new java.awt.Dimension(155, 465));
        controlArea.setPreferredSize(new java.awt.Dimension(155, 465));

        btnCourseOffering.setText("Course Offering");
        btnCourseOffering.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseOfferingActionPerformed(evt);
            }
        });

        btnStudentRegistration.setText("Student Registration");
        btnStudentRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentRegistrationActionPerformed(evt);
            }
        });

        btnFinanceReports.setText("Finance Reports");
        btnFinanceReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinanceReportsActionPerformed(evt);
            }
        });

        btnInstitutionalReports.setText("Institutional Reports");
        btnInstitutionalReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstitutionalReportsActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 204, 204));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        lblWelcomeTitle.setText("Welcome!");

        javax.swing.GroupLayout controlAreaLayout = new javax.swing.GroupLayout(controlArea);
        controlArea.setLayout(controlAreaLayout);
        controlAreaLayout.setHorizontalGroup(
            controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlAreaLayout.createSequentialGroup()
                .addGroup(controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlAreaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnInstitutionalReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStudentRegistration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFinanceReports, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCourseOffering, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(controlAreaLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnLogout))
                    .addGroup(controlAreaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(controlAreaLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblWelcomeTitle)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        controlAreaLayout.setVerticalGroup(
            controlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlAreaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblWelcomeTitle)
                .addGap(37, 37, 37)
                .addComponent(btnCourseOffering)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStudentRegistration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinanceReports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInstitutionalReports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(90, 90, 90))
        );

        splitPane.setLeftComponent(controlArea);

        workArea.setBackground(new java.awt.Color(204, 255, 204));
        workArea.setMaximumSize(new java.awt.Dimension(600, 465));
        workArea.setMinimumSize(new java.awt.Dimension(600, 465));
        workArea.setPreferredSize(new java.awt.Dimension(600, 465));
        workArea.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseOfferingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseOfferingActionPerformed
        // TODO add your handling code here:
        workAreaLayout.show(workArea, "CourseOffering");
    }//GEN-LAST:event_btnCourseOfferingActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // 1. Clear the session (Assumes a SessionManager.clearSession() method)
        // SessionManager.clearSession(); 
        
        // 2. Display success message
        JOptionPane.showMessageDialog(this, "Logged out successfully!", "Logout", JOptionPane.INFORMATION_MESSAGE);
        
        // 3. Navigate back to the Login screen on the MainFrame
        if (mainFrame != null) {
            // This method MUST exist in MainFrame.java to fulfill the requirement
            mainFrame.showLoginPanel(); 
        }                                                                              
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnStudentRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentRegistrationActionPerformed
        // TODO add your handling code here:
        workAreaLayout.show(workArea, "StudentRegistration");
    }//GEN-LAST:event_btnStudentRegistrationActionPerformed

    private void btnFinanceReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinanceReportsActionPerformed
        // TODO add your handling code here:
        workAreaLayout.show(workArea, "FinanceReports");
    }//GEN-LAST:event_btnFinanceReportsActionPerformed

    private void btnInstitutionalReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstitutionalReportsActionPerformed
        // TODO add your handling code here:
        workAreaLayout.show(workArea, "InstitutionalReports");
    }//GEN-LAST:event_btnInstitutionalReportsActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        ProfileManagementDialog dialog = new ProfileManagementDialog(mainFrame, true, loggedInRegistrar.getPerson());
        dialog.setVisible(true);
        
        // 2. After the dialog closes, refresh the welcome title if the name was updated
        updateWelcomeLabel();
    }//GEN-LAST:event_btnProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseOffering;
    private javax.swing.JButton btnFinanceReports;
    private javax.swing.JButton btnInstitutionalReports;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnStudentRegistration;
    private javax.swing.JPanel controlArea;
    private javax.swing.JLabel lblWelcomeTitle;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
