/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.FacultyRole;
import Model.User.UserAccount;
import Model.User.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import UI.LoginPanel;
/**
 *
 * @author jayan
 */
public class FacultyDashboardJPanel extends javax.swing.JPanel {
    private JPanel mainWorkArea;  // reference to MainFrame work area
    private UserAccountDirectory accountDirectory;
    private UserAccount userAccount;
    /**
     * Creates new form FacultyDashboardJPanel
     */
    public FacultyDashboardJPanel(JPanel mainWorkArea, UserAccountDirectory accountDirectory, UserAccount userAccount) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.accountDirectory = accountDirectory;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        FacultyControlArea = new javax.swing.JPanel();
        lblFacultyDashboard = new javax.swing.JLabel();
        btnCourseManagement = new javax.swing.JButton();
        btnStudentManagement = new javax.swing.JButton();
        btnPerfRep = new javax.swing.JButton();
        btnProfileManagement = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnTutionInsights = new javax.swing.JButton();
        FacultyWorkArea = new javax.swing.JPanel();

        setBackground(new java.awt.Color(204, 255, 204));
        setMaximumSize(new java.awt.Dimension(600, 465));
        setMinimumSize(new java.awt.Dimension(600, 465));
        setPreferredSize(new java.awt.Dimension(600, 465));

        FacultyControlArea.setBackground(new java.awt.Color(204, 255, 204));

        lblFacultyDashboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFacultyDashboard.setText("Faculty Dashboard");

        btnCourseManagement.setText("Course Management");
        btnCourseManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseManagementActionPerformed(evt);
            }
        });

        btnStudentManagement.setText("Student Management");
        btnStudentManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentManagementActionPerformed(evt);
            }
        });

        btnPerfRep.setText("Performance and Reporting");
        btnPerfRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfRepActionPerformed(evt);
            }
        });

        btnProfileManagement.setText("Profile Mangement");
        btnProfileManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileManagementActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnTutionInsights.setText("Tution Insights");
        btnTutionInsights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutionInsightsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FacultyControlAreaLayout = new javax.swing.GroupLayout(FacultyControlArea);
        FacultyControlArea.setLayout(FacultyControlAreaLayout);
        FacultyControlAreaLayout.setHorizontalGroup(
            FacultyControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FacultyControlAreaLayout.createSequentialGroup()
                .addGroup(FacultyControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCourseManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStudentManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProfileManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPerfRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTutionInsights, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(FacultyControlAreaLayout.createSequentialGroup()
                .addGroup(FacultyControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FacultyControlAreaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFacultyDashboard))
                    .addGroup(FacultyControlAreaLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnLogout)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FacultyControlAreaLayout.setVerticalGroup(
            FacultyControlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FacultyControlAreaLayout.createSequentialGroup()
                .addComponent(lblFacultyDashboard)
                .addGap(32, 32, 32)
                .addComponent(btnCourseManagement)
                .addGap(18, 18, 18)
                .addComponent(btnStudentManagement)
                .addGap(18, 18, 18)
                .addComponent(btnPerfRep)
                .addGap(18, 18, 18)
                .addComponent(btnProfileManagement)
                .addGap(18, 18, 18)
                .addComponent(btnTutionInsights)
                .addGap(18, 18, 18)
                .addComponent(btnLogout)
                .addGap(0, 180, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(FacultyControlArea);

        FacultyWorkArea.setBackground(new java.awt.Color(204, 255, 204));
        FacultyWorkArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(FacultyWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfileManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileManagementActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnProfileManagementActionPerformed

    private void btnCourseManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseManagementActionPerformed
        // TODO add your handling code here:
        CourseManagementJPanel coursePanel = new CourseManagementJPanel(FacultyWorkArea, userAccount);
        FacultyWorkArea.add("CourseManagementJPanel", coursePanel);
        CardLayout layout = (CardLayout) FacultyWorkArea.getLayout();
        layout.next(FacultyWorkArea);
    }//GEN-LAST:event_btnCourseManagementActionPerformed

    private void btnStudentManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentManagementActionPerformed
        // TODO add your handling code here:
        StudentGradingJPanel studentPanel = new StudentGradingJPanel(FacultyWorkArea, userAccount);
        FacultyWorkArea.add("StudentGradingJPanel", studentPanel);
        CardLayout layout = (CardLayout) FacultyWorkArea.getLayout();
        layout.next(FacultyWorkArea);
    }//GEN-LAST:event_btnStudentManagementActionPerformed

    private void btnPerfRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfRepActionPerformed
        // TODO add your handling code here:
        PerformanceReportJPanel reportPanel = new PerformanceReportJPanel(FacultyWorkArea, userAccount);
        FacultyWorkArea.add("PerformanceReportJPanel", reportPanel);
        CardLayout layout = (CardLayout) FacultyWorkArea.getLayout();
        layout.next(FacultyWorkArea);
    }//GEN-LAST:event_btnPerfRepActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnTutionInsightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutionInsightsActionPerformed
        // TODO add your handling code here:
        TutionInsightsJPanel insightsPanel = new TutionInsightsJPanel(FacultyWorkArea, userAccount);
        FacultyWorkArea.add("TuitionInsightsJPanel", insightsPanel);
        CardLayout layout = (CardLayout) FacultyWorkArea.getLayout();
        layout.next(FacultyWorkArea);
    }//GEN-LAST:event_btnTutionInsightsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FacultyControlArea;
    private javax.swing.JPanel FacultyWorkArea;
    private javax.swing.JButton btnCourseManagement;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPerfRep;
    private javax.swing.JButton btnProfileManagement;
    private javax.swing.JButton btnStudentManagement;
    private javax.swing.JButton btnTutionInsights;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblFacultyDashboard;
    // End of variables declaration//GEN-END:variables
}
