/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.FacultyRole;

import Model.*;
import Model.Faculty;
import Model.User.UserAccount;
import Model.accesscontrol.ConfigureJTable; // Central Data Source
import javax.swing.JPanel;
import java.util.*;
import java.util.stream.Collectors;
/**
 *
 * @author talha
 */
public class TutionInsightsJPanel extends javax.swing.JPanel {
    private JPanel workArea;
    private UserAccount userAccount;
    private Faculty faculty;
    // Map CourseID+Name -> TuitionData (for quick lookup)
    private Map<String, TuitionData> courseTuitionMap; 
    private static final double TUITION_PER_CREDIT = 1500.0;
    
    // Inner class to hold calculated results based on a live CourseOffering
    private class TuitionData {
        CourseOffering courseOffering;
        int totalStudents;
        double totalTuitionCollected;
        
        public TuitionData(CourseOffering courseOffering) {
            this.courseOffering = courseOffering;
            // Get live enrolled count from the central CourseOffering object
            this.totalStudents = courseOffering.getEnrolledCount(); 
            this.totalTuitionCollected = calculateTuition();
        }
        
        private double calculateTuition() {
            int credits = courseOffering.getCourse().getCredits();
            // Assuming all enrolled students paid the full tuition amount
            return totalStudents * credits * TUITION_PER_CREDIT;
        }
    }
    
    public TutionInsightsJPanel(JPanel workArea, UserAccount userAccount) {
        this.workArea = workArea;
        this.userAccount = userAccount;
        this.faculty = (Faculty) userAccount.getProfile();
        initComponents();
        
        initializeLiveData(); // FIX: Use live data setup
        populateCourseDropdown();
        
        // Add listener
        cmbSelectCourse.addActionListener(e -> displayTuitionInsights());
    }
    
    /**
     * Initializes tuition insights by pulling live enrollment and course data
     * from ConfigureJTable.
     */
    private void initializeLiveData() {
        courseTuitionMap = new HashMap<>();
        int facultyUNID = faculty.getPerson().getUNID();
        
        // Filter ConfigureJTable's course list by the current faculty's UNID
        ConfigureJTable.courseOfferingList.stream()
            .filter(o -> o.getFaculty() != null && o.getFaculty().getPerson().getUNID() == facultyUNID)
            .forEach(offering -> {
                // Create the data object using the live CourseOffering
                TuitionData tuitionData = new TuitionData(offering);
                String courseKey = offering.getCourseID() + " - " + offering.getCourseName();
                
                courseTuitionMap.put(courseKey, tuitionData);
            });
    }

    /**
     * Populate course dropdown
     */
    private void populateCourseDropdown() {
        cmbSelectCourse.removeAllItems();
        cmbSelectCourse.addItem("-- Select Course --");
        
        // Populate dropdown with the live courses assigned to the faculty
        for (String courseName : courseTuitionMap.keySet()) {
            cmbSelectCourse.addItem(courseName);
        }
    }

    /**
     * Display tuition insights for selected course
     */
    private void displayTuitionInsights() {
        String selectedCourse = (String) cmbSelectCourse.getSelectedItem();
        
        if (selectedCourse == null || selectedCourse.equals("-- Select Course --")) {
            clearFields();
            return;
        }
        
        TuitionData tuitionData = courseTuitionMap.get(selectedCourse);
        
        if (tuitionData != null) {
            // Display total number of students
            txtTotalStudents.setText(String.valueOf(tuitionData.totalStudents));
            
            // Display total tuition fee collected
            txtTotalFee.setText(String.format("$%,.2f", tuitionData.totalTuitionCollected));
        } else {
            clearFields();
        }
    }

    /**
     * Clear all fields
     */
    private void clearFields() {
        txtTotalStudents.setText("");
        txtTotalFee.setText("");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTotalFee = new javax.swing.JTextField();
        cmbSelectCourse = new javax.swing.JComboBox<>();
        lblInsights = new javax.swing.JLabel();
        txtTotalStudents = new javax.swing.JTextField();
        lblSelectCourse = new javax.swing.JLabel();
        lblTotalStudents = new javax.swing.JLabel();
        lblTotalFee = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));

        lblInsights.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblInsights.setText("Tution/Enrollment Insights");

        lblSelectCourse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSelectCourse.setText("Select Course :");

        lblTotalStudents.setText("Total Number of Students");

        lblTotalFee.setText("Total Tuition Fee Collected");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblInsights)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblSelectCourse)
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTotalStudents)
                                .addComponent(cmbSelectCourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTotalFee))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotalStudents)
                            .addComponent(lblTotalFee))
                        .addGap(113, 113, 113)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblInsights)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectCourse)
                    .addComponent(cmbSelectCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalStudents)
                    .addComponent(txtTotalStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalFee)
                    .addComponent(txtTotalFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(240, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbSelectCourse;
    private javax.swing.JLabel lblInsights;
    private javax.swing.JLabel lblSelectCourse;
    private javax.swing.JLabel lblTotalFee;
    private javax.swing.JLabel lblTotalStudents;
    private javax.swing.JTextField txtTotalFee;
    private javax.swing.JTextField txtTotalStudents;
    // End of variables declaration//GEN-END:variables
}
