/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AdminRole;

import Model.User.UserAccount;
import Model.User.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jayan
 */
public class AdminDashboardJPanel extends javax.swing.JPanel {
    
    private UserAccountDirectory accountDirectory;
    private UserAccount account;
    private JPanel mainWorkArea;

    /**
     * Creates new form AdminDashboardJPanel
     */
    public AdminDashboardJPanel(JPanel workArea, UserAccountDirectory accountDirectory, UserAccount account) {
        initComponents();
        this.accountDirectory = accountDirectory;
        this.account = account;
        this.mainWorkArea = workArea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnStudentFacultySearch = new javax.swing.JButton();
        btnAnalyticsDashboard = new javax.swing.JButton();
        btnPersonRegistration = new javax.swing.JButton();
        btnUserAccountManagement = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnPersonProfile = new javax.swing.JButton();
        btnRegistrarSearch = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setBackground(new java.awt.Color(204, 255, 204));
        setMaximumSize(new java.awt.Dimension(600, 465));
        setMinimumSize(new java.awt.Dimension(600, 465));

        controlPanel.setBackground(new java.awt.Color(255, 255, 204));
        controlPanel.setMaximumSize(new java.awt.Dimension(155, 465));
        controlPanel.setMinimumSize(new java.awt.Dimension(155, 465));
        controlPanel.setPreferredSize(new java.awt.Dimension(155, 465));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Welcome Admin");

        btnStudentFacultySearch.setText("StudentFacultySearch");
        btnStudentFacultySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentFacultySearchActionPerformed(evt);
            }
        });

        btnAnalyticsDashboard.setText("Analytics Dashboard");
        btnAnalyticsDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyticsDashboardActionPerformed(evt);
            }
        });

        btnPersonRegistration.setText("Person Registration");
        btnPersonRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonRegistrationActionPerformed(evt);
            }
        });

        btnUserAccountManagement.setText("User Account Management");
        btnUserAccountManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserAccountManagementActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnPersonProfile.setText("Profile");
        btnPersonProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonProfileActionPerformed(evt);
            }
        });

        btnRegistrarSearch.setText("RegistrarSearch");
        btnRegistrarSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnStudentFacultySearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUserAccountManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnRegistrarSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPersonRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, controlPanelLayout.createSequentialGroup()
                        .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnPersonProfile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAnalyticsDashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblTitle))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitle)
                .addGap(40, 40, 40)
                .addComponent(btnPersonRegistration)
                .addGap(28, 28, 28)
                .addComponent(btnUserAccountManagement)
                .addGap(18, 18, 18)
                .addComponent(btnStudentFacultySearch)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarSearch)
                .addGap(18, 18, 18)
                .addComponent(btnAnalyticsDashboard)
                .addGap(18, 18, 18)
                .addComponent(btnPersonProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(42, 42, 42))
        );

        splitPane.setLeftComponent(controlPanel);

        workArea.setBackground(new java.awt.Color(204, 255, 204));
        workArea.setMaximumSize(new java.awt.Dimension(600, 465));
        workArea.setMinimumSize(new java.awt.Dimension(600, 465));
        workArea.setPreferredSize(new java.awt.Dimension(600, 465));
        workArea.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserAccountManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAccountManagementActionPerformed
        // TODO add your handling code here:
        UserAccountManagementJPanel panel = new UserAccountManagementJPanel(accountDirectory);
        this.splitPane.setRightComponent(panel);
    }//GEN-LAST:event_btnUserAccountManagementActionPerformed

    private void btnPersonRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonRegistrationActionPerformed
        // TODO add your handling code here:
        PersonRegistrationJPanel panel = new PersonRegistrationJPanel(accountDirectory);
        this.splitPane.setRightComponent(panel);
    }//GEN-LAST:event_btnPersonRegistrationActionPerformed

    private void btnStudentFacultySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentFacultySearchActionPerformed
        // TODO add your handling code here:
        StudentFacultySearchJPanel panel = new StudentFacultySearchJPanel(accountDirectory);
        this.splitPane.setRightComponent(panel);
    }//GEN-LAST:event_btnStudentFacultySearchActionPerformed

    private void btnRegistrarSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSearchActionPerformed
        // TODO add your handling code here:
        RegistrarSearchJPanel panel = new  RegistrarSearchJPanel();
        this.splitPane.setRightComponent(panel);
    }//GEN-LAST:event_btnRegistrarSearchActionPerformed

    private void btnAnalyticsDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyticsDashboardActionPerformed
        // TODO add your handling code here:
        AnalyticsDashboardJPanel panel = new AnalyticsDashboardJPanel();
        this.splitPane.setRightComponent(panel);
    }//GEN-LAST:event_btnAnalyticsDashboardActionPerformed

    private void btnPersonProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPersonProfileActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Logged out successfully!", "Logout", JOptionPane.INFORMATION_MESSAGE);
        
        this.mainWorkArea.remove(this);
        CardLayout layout = (CardLayout) this.mainWorkArea.getLayout();
        layout.previous(this.mainWorkArea); 
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalyticsDashboard;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPersonProfile;
    private javax.swing.JButton btnPersonRegistration;
    private javax.swing.JButton btnRegistrarSearch;
    private javax.swing.JButton btnStudentFacultySearch;
    private javax.swing.JButton btnUserAccountManagement;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
