/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AdminRole;

import Model.Admin;
import Model.User.UserAccount;
import Model.User.UserAccountDirectory;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gagan
 */
public class UserAccountManagementJPanel extends javax.swing.JPanel {
    
    private UserAccountDirectory accountDirectory;

    /**
     * Creates new form UserAccountManagementJPanel
     */
    public UserAccountManagementJPanel(UserAccountDirectory directory) {
        initComponents();
        this.accountDirectory = directory;
        this.refreshTable();
        // hide the internal UNID column to prevent accidental edits/visibility
        hideUnidColumn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserAccountManagement = new javax.swing.JTable();
        btnModify = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setMaximumSize(new java.awt.Dimension(600, 465));
        setMinimumSize(new java.awt.Dimension(600, 465));

        tblUserAccountManagement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "UNID", "Name", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUserAccountManagement);

        btnModify.setText("Modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnModify)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModify)
                    .addComponent(btnDelete))
                .addContainerGap(188, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        int selectedRow = tblUserAccountManagement.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to modify");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblUserAccountManagement.getModel();
        int modelRow = tblUserAccountManagement.convertRowIndexToModel(selectedRow);

        // Get values directly from the model
        Object nameObj = model.getValueAt(modelRow, 1);
        Object usernameObj = model.getValueAt(modelRow, 2);
        Object passwordObj = model.getValueAt(modelRow, 3);
        Object unidObj = model.getValueAt(modelRow, 0);

        String name = nameObj == null ? "" : nameObj.toString();
        String username = usernameObj == null ? "" : usernameObj.toString();
        String password = passwordObj == null ? "" : passwordObj.toString();
        String unid = unidObj == null ? "" : unidObj.toString();

        if (unid.isEmpty()) {
             JOptionPane.showMessageDialog(this, "Unable to determine selected user account (missing UNID).");
             return;
        }

        UserAccount account = accountDirectory.findUserAccount(unid);
        if (account == null) {
            JOptionPane.showMessageDialog(this, "Selected user account could not be found.");
            return;
        }

        // --- Data Update Logic (Direct modification to UserAccount/Person) ---
        account.setUsername(username);
        account.setPassword(password);
        account.getProfile().getPerson().setName(name);

        refreshTable();

        JOptionPane.showMessageDialog(this, "User account updated successfully!");
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tblUserAccountManagement.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete this user account?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            DefaultTableModel model = (DefaultTableModel) tblUserAccountManagement.getModel();
            int modelRow = tblUserAccountManagement.convertRowIndexToModel(selectedRow);
            Object unidObj = model.getValueAt(modelRow, 0);
            
            String unid = unidObj == null ? "" : unidObj.toString();
            UserAccount account = accountDirectory.findUserAccount(unid);
            
            if (account != null) {
                accountDirectory.getUserAccountList().remove(account);
                refreshTable();
                JOptionPane.showMessageDialog(this, "User account deleted successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Selected user account could not be found.");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void refreshTable() {
        DefaultTableModel model = (DefaultTableModel)tblUserAccountManagement.getModel();
        model.setRowCount(0);
        
        for(UserAccount ua: this.accountDirectory.getUserAccountList()) {
            if(ua.getProfile() instanceof Admin) continue;
            Object[] obj = new Object[4];
            obj[0] = ua.getProfile().getPerson().getUNID();
            // store the name string instead of the UserAccount object to avoid replacement when edited
            obj[1] = ua.getProfile().getPerson().getName();
            obj[2] = ua.getUsername();
            obj[3] = ua.getPassword();
            model.addRow(obj);
        }
    }

    private void hideUnidColumn() {
        // Ensure table has a column model and at least one column
        if (tblUserAccountManagement.getColumnModel().getColumnCount() > 0) {
            try {
                javax.swing.table.TableColumn col = tblUserAccountManagement.getColumnModel().getColumn(0);
                col.setMinWidth(0);
                col.setMaxWidth(0);
                col.setPreferredWidth(0);
                col.setResizable(false);
            } catch (Exception ex) {
                // ignore - this is a UI convenience, not critical
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUserAccountManagement;
    // End of variables declaration//GEN-END:variables
}
