/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.StudentRole;

import Model.*;
import Model.User.UserAccount;
import Model.User.UserAccountDirectory;
import Model.ProfileManagementDialog;
import UI.MainJFrame;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.JFrame; 
import java.util.Arrays;
/**
 *
 * @author jayan
 */
public class StudentDashboardJPanel extends javax.swing.JPanel {
    
    private UserAccount userAccount;
    private UserAccountDirectory accountDirectory;
    private JPanel mainWorkArea; // The main Content Pane (workArea from MainJFrame)
    private Student loggedInStudent;
    
    // Panel References (Instantiated once, then reused or refreshed)
    private CourseRegistrationJPanel courseRegistrationPanel;
    private GraduationAuditJPanel graduationAuditPanel;
    private TranscriptJPanel transcriptPanel;
    private TuitionPaymentJPanel tuitionPaymentPanel;
    
    public StudentDashboardJPanel(JPanel mainWorkArea, UserAccountDirectory accountDirectory, UserAccount account) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.accountDirectory = accountDirectory;
        this.userAccount = account;
        
        if (userAccount.getProfile() instanceof Student) {
            this.loggedInStudent = (Student) userAccount.getProfile();
        } else {
             this.loggedInStudent = null; 
             JOptionPane.showMessageDialog(this, "Profile error. Please log in again.", "Error", JOptionPane.ERROR_MESSAGE);
             return;
        }
        
        lblTitle.setText("Welcome " + loggedInStudent.getPerson().getName());
        workArea.setLayout(new CardLayout());
    }


    /**
     * Helper method to switch to a feature panel.
     */
    private void showFeaturePanel(String panelName, JPanel panel) {
        CardLayout layout = (CardLayout) workArea.getLayout();
        
        // This logic ensures the panel is added only once to the container
        boolean isPanelAdded = false;
        for (java.awt.Component comp : workArea.getComponents()) {
            if (comp.getName() != null && comp.getName().equals(panelName)) {
                isPanelAdded = true;
                break;
            }
        }

        if (!isPanelAdded) {
            workArea.add(panel, panelName);
            panel.setName(panelName); // Set name for future reference
        }
        layout.show(workArea, panelName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnTranscript = new javax.swing.JButton();
        btnTuitionPayment = new javax.swing.JButton();
        btnCourseRegistration = new javax.swing.JButton();
        btnGraduationAudit = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnPersonProfile = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setBackground(new java.awt.Color(204, 255, 204));
        setMaximumSize(new java.awt.Dimension(600, 465));
        setMinimumSize(new java.awt.Dimension(600, 465));

        controlPanel.setBackground(new java.awt.Color(255, 255, 204));
        controlPanel.setMaximumSize(new java.awt.Dimension(155, 465));
        controlPanel.setMinimumSize(new java.awt.Dimension(155, 465));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Welcome Student");

        btnTranscript.setText("Transcript");
        btnTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranscriptActionPerformed(evt);
            }
        });

        btnTuitionPayment.setText("Tuition Payment");
        btnTuitionPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTuitionPaymentActionPerformed(evt);
            }
        });

        btnCourseRegistration.setText("Course Registration");
        btnCourseRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseRegistrationActionPerformed(evt);
            }
        });

        btnGraduationAudit.setText("Graduation Audit");
        btnGraduationAudit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraduationAuditActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnPersonProfile.setText("Profile");
        btnPersonProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGraduationAudit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(btnTranscript, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTuitionPayment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPersonProfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(controlPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnCourseRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTitle)
                .addGap(84, 84, 84)
                .addComponent(btnGraduationAudit)
                .addGap(18, 18, 18)
                .addComponent(btnTranscript)
                .addGap(18, 18, 18)
                .addComponent(btnTuitionPayment)
                .addGap(18, 18, 18)
                .addComponent(btnPersonProfile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(19, 19, 19))
            .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(controlPanelLayout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(btnCourseRegistration)
                    .addContainerGap(349, Short.MAX_VALUE)))
        );

        splitPane.setLeftComponent(controlPanel);

        workArea.setBackground(new java.awt.Color(204, 255, 204));
        workArea.setMaximumSize(new java.awt.Dimension(600, 465));
        workArea.setMinimumSize(new java.awt.Dimension(600, 465));
        workArea.setPreferredSize(new java.awt.Dimension(600, 465));
        workArea.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGraduationAuditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraduationAuditActionPerformed
        // TODO add your handling code here:
        if (graduationAuditPanel == null) {
            graduationAuditPanel = new GraduationAuditJPanel(workArea, userAccount);
        }
        // CRITICAL: We must re-instantiate/re-audit the panel every time 
        // to reflect the latest earned credits/grades/etc.
        graduationAuditPanel = new GraduationAuditJPanel(workArea, userAccount);
        showFeaturePanel("GraduationAuditJPanel", graduationAuditPanel);
    }//GEN-LAST:event_btnGraduationAuditActionPerformed

    private void btnCourseRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseRegistrationActionPerformed
        // TODO add your handling code here:
        // FIX: Always refresh this panel to update credit hour status (CRITICAL)
        courseRegistrationPanel = new CourseRegistrationJPanel(workArea, userAccount);
        showFeaturePanel("CourseRegistrationJPanel", courseRegistrationPanel);

    }//GEN-LAST:event_btnCourseRegistrationActionPerformed

    private void btnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranscriptActionPerformed
        // TODO add your handling code here:
        // --- FINANCIAL GATEKEEPER CHECK (Assignment Requirement) ---
        if (loggedInStudent != null && loggedInStudent.getTuitionBalance() > 0) {
            JOptionPane.showMessageDialog(this, 
                "You have an outstanding tuition balance of $" + String.format("%.2f", loggedInStudent.getTuitionBalance()) +
                "\n\nPlease pay your tuition to view your transcript.", 
                "Tuition Balance Due", JOptionPane.WARNING_MESSAGE);
            
            // Offer to go to payment page
            int choice = JOptionPane.showConfirmDialog(this, "Would you like to go to the Tuition Payment page now?", "Pay Tuition", JOptionPane.YES_NO_OPTION);
            
            if (choice == JOptionPane.YES_OPTION) {
                btnTuitionPaymentActionPerformed(evt);
            }
            return;
        }
        
        // If paid, show transcript (re-instantiating to recalculate GPA)
        transcriptPanel = new TranscriptJPanel(workArea, userAccount);
        showFeaturePanel("TranscriptJPanel", transcriptPanel);
    }//GEN-LAST:event_btnTranscriptActionPerformed

    private void btnTuitionPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTuitionPaymentActionPerformed
        // TODO add your handling code here:
        if (tuitionPaymentPanel == null) {
            tuitionPaymentPanel = new TuitionPaymentJPanel(workArea, userAccount);
        }
        // Always re-instantiate payment panel to refresh balances from central store
        tuitionPaymentPanel = new TuitionPaymentJPanel(workArea, userAccount);
        showFeaturePanel("TuitionPaymentJPanel", tuitionPaymentPanel);
    }//GEN-LAST:event_btnTuitionPaymentActionPerformed

    private void btnPersonProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonProfileActionPerformed
        // TODO add your handling code here:
        Person person = userAccount.getProfile().getPerson();
        java.awt.Window win = SwingUtilities.getWindowAncestor(this);
        JFrame parentFrame = (win instanceof JFrame) ? (JFrame) win : null;
        
        // ProfileManagementDialog is reusable across all roles
        ProfileManagementDialog dialog = new ProfileManagementDialog(parentFrame, true, person);
        dialog.setVisible(true);
        
        // Optional: Refresh dashboard title if name was changed
        lblTitle.setText("Welcome " + loggedInStudent.getPerson().getName());
    }//GEN-LAST:event_btnPersonProfileActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Logged out successfully!", "Logout", JOptionPane.INFORMATION_MESSAGE);
        
        MainJFrame mainFrame = (MainJFrame) SwingUtilities.getWindowAncestor(this);
        if (mainFrame != null) {
            mainFrame.showLoginPanel(); 
        }
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCourseRegistration;
    private javax.swing.JButton btnGraduationAudit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPersonProfile;
    private javax.swing.JButton btnTranscript;
    private javax.swing.JButton btnTuitionPayment;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
