/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.StudentRole;
import Model.FinancialRecord;
import Model.Student;
import Model.User.UserAccount;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MALLESH
 */
public class TuitionPaymentJPanel extends javax.swing.JPanel {
  private UserAccount userAccount;
    private Student student;
    private ArrayList<FinancialRecord> paymentHistory;
    private double currentBalance;
    private double outstandingBalance;


    /**
     * Creates new form TuitionPaymentJPanel
     */
    public TuitionPaymentJPanel() {
      this.paymentHistory = new ArrayList<>();
        initDemoData();
        populatePaymentTable();
        refreshBalances();
    }
         public TuitionPaymentJPanel(UserAccount account, ArrayList<FinancialRecord> records) {
        initComponents();
        this.userAccount = account;
        this.student = (Student) account.getProfile();
        this.paymentHistory = records != null ? records : new ArrayList<>();
        txtStudentName.setText(student.getPerson().getName());
        calculateBalances();
        populatePaymentTable();
        refreshBalances();
         }
         
      private void initDemoData() {
        // Fake data for testing UI
        txtStudentName.setText("John Doe");
        this.currentBalance = 2000.00;
        this.outstandingBalance = 6000.00;
        paymentHistory.add(new FinancialRecord("TXN-1001", null, 3000, "BILLED", "Fall 2025", "2025-09-05"));
        paymentHistory.add(new FinancialRecord("TXN-1002", null, 1000, "PAID", "Fall 2025", "2025-09-20"));
    }

    private void calculateBalances() {
        double billed = 0, paid = 0;
        for (FinancialRecord fr : paymentHistory) {
            if (fr.getType().equalsIgnoreCase("BILLED")) billed += fr.getAmount();
            if (fr.getType().equalsIgnoreCase("PAID")) paid += fr.getAmount();
        }
        outstandingBalance = billed - paid;
        currentBalance = paid;
    }

    private void refreshBalances() {
        txtCurrentBalance.setText(String.format("$%.2f", currentBalance));
        txtOutstandingTuition.setText(String.format("$%.2f", outstandingBalance));
    }

    private void populatePaymentTable() {
        DefaultTableModel model = (DefaultTableModel) tblPaymentHistory.getModel();
        model.setRowCount(0);
        for (FinancialRecord fr : paymentHistory) {
            Object[] row = new Object[6];
            row[0] = fr.getDate();
            row[1] = fr.getTransactionID();
            row[2] = fr.getType();
            row[3] = fr.getSemester();
            row[4] = String.format("$%.2f", fr.getAmount());
            row[5] = fr.getType().equalsIgnoreCase("PAID") ? String.format("$%.2f", currentBalance) : "-";
            model.addRow(row);
        }
    }

    private String getCurrentDate() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        return sdf.format(new Date());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        txtCurrentBalance = new javax.swing.JTextField();
        lblCurrentBalance = new javax.swing.JLabel();
        lblOutstandingBalance = new javax.swing.JLabel();
        txtOutstandingTuition = new javax.swing.JTextField();
        btnPayBill = new javax.swing.JButton();
        lblPaymentAmount = new javax.swing.JLabel();
        txtPaymentAmount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaymentHistory = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setMaximumSize(new java.awt.Dimension(600, 465));
        setMinimumSize(new java.awt.Dimension(600, 465));

        jLabel1.setText("Tuition Payment Portal");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Account Summary:");

        lblStudentName.setText("Student Name:");

        txtStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNameActionPerformed(evt);
            }
        });

        txtCurrentBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurrentBalanceActionPerformed(evt);
            }
        });

        lblCurrentBalance.setText("Current Balance:");

        lblOutstandingBalance.setText("Outstanding Tuition:");

        txtOutstandingTuition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOutstandingTuitionActionPerformed(evt);
            }
        });

        btnPayBill.setText("Pay Bill");
        btnPayBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayBillActionPerformed(evt);
            }
        });

        lblPaymentAmount.setText("Payment Amount:");

        txtPaymentAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentAmountActionPerformed(evt);
            }
        });

        tblPaymentHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Transaction ID", "Transaction Type", "Course ID", "Amount", "Balance After Transaction"
            }
        ));
        jScrollPane1.setViewportView(tblPaymentHistory);

        jLabel8.setText("Payment History");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblOutstandingBalance)
                                        .addComponent(lblStudentName, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(lblCurrentBalance))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCurrentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOutstandingTuition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblPaymentAmount)
                                .addGap(18, 18, 18)
                                .addComponent(txtPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPayBill))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(229, 229, 229)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCurrentBalance, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCurrentBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOutstandingBalance)
                            .addComponent(txtOutstandingTuition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblStudentName)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaymentAmount)
                    .addComponent(txtPaymentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPayBill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPaymentAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentAmountActionPerformed

    private void txtStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNameActionPerformed

    private void txtCurrentBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurrentBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurrentBalanceActionPerformed

    private void txtOutstandingTuitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOutstandingTuitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOutstandingTuitionActionPerformed

    private void btnPayBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayBillActionPerformed
        // TODO add your handling code here:
       try {
            double paymentAmount = Double.parseDouble(txtPaymentAmount.getText().trim());
            if (paymentAmount <= 0) {
                JOptionPane.showMessageDialog(this, "Enter a valid payment amount.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (paymentAmount > outstandingBalance) {
                JOptionPane.showMessageDialog(this, "Payment exceeds outstanding tuition.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Update balances
            outstandingBalance -= paymentAmount;
            currentBalance += paymentAmount;

            // Add new FinancialRecord
            String transactionId = "TXN-" + System.currentTimeMillis();
            FinancialRecord newPayment = new FinancialRecord(
                    transactionId,
                    student,
                    paymentAmount,
                    "PAID",
                    "Fall 2025", // You can replace with current semester dynamically
                    getCurrentDate()
            );

            paymentHistory.add(newPayment);

            JOptionPane.showMessageDialog(this, "Payment successful! Thank you.", "Payment Confirmation", JOptionPane.INFORMATION_MESSAGE);
            populatePaymentTable();
            refreshBalances();
            txtPaymentAmount.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a numeric amount.", "Error", JOptionPane.ERROR_MESSAGE);
        }                           

    }//GEN-LAST:event_btnPayBillActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPayBill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurrentBalance;
    private javax.swing.JLabel lblOutstandingBalance;
    private javax.swing.JLabel lblPaymentAmount;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JTable tblPaymentHistory;
    private javax.swing.JTextField txtCurrentBalance;
    private javax.swing.JTextField txtOutstandingTuition;
    private javax.swing.JTextField txtPaymentAmount;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables
}
