/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Department;
import Model.ProfileEnum;
import static Model.ProfileEnum.ADMIN;
import static Model.ProfileEnum.FACULTY;
import static Model.ProfileEnum.REGISTRAR;
import Model.User.UserAccount;
import Model.User.UserAccountDirectory;
import UI.AdminRole.AdminDashboardJPanel;
import UI.FacultyRole.FacultyDashboardJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gagan
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    
    private JPanel workArea;

    // --- Dashboard Panel References (for checking if instantiated) ---
    private JPanel adminDashboardPanel;
    private JPanel facultyDashboardPanel;
    private JPanel studentDashboardPanel;
    private JPanel registrarDashboardPanel;
    private UserAccountDirectory accountDirectory;
    
    public LoginPanel(JPanel workArea) {
        initComponents();
        this.workArea = workArea;
        this.accountDirectory = new UserAccountDirectory();
        this.accountDirectory.newUserAccount("admin", "0000",
                "admin", "pass", ProfileEnum.ADMIN,
                null, "email@email.com");
        this.accountDirectory.newUserAccount("faculty", "1111", "faculty", "pass", ProfileEnum.FACULTY, null, "facultyemail@gmail.com");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        lblUsername.setText("Username:");

        lblPassword.setText("Password:");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(255, 204, 204));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUsername)
                            .addComponent(lblPassword))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername)
                            .addComponent(jPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(btnLogin)))
                .addContainerGap(321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addGap(36, 36, 36)
                .addComponent(btnLogin)
                .addContainerGap(252, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText();
        String password = new String(jPasswordField.getPassword());

        // 1. Input Validation (Crucial for grading)
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username and Password cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. Authentication (REPLACE with your AuthService.authenticate method call)
        UserAccount authenticatedUser = authenticate(username, password);

        if (authenticatedUser != null) {
            JOptionPane.showMessageDialog(this, "Login Successful! Role: " + authenticatedUser.getProfile().getRole(), "Success", JOptionPane.INFORMATION_MESSAGE);

            // 3. Call the central method to switch the view to the appropriate dashboard
            showDashboard(authenticatedUser);

            // Clear fields after successful login
            txtUsername.setText("");
            jPasswordField.setText("");
        } else {
            // Failure
            JOptionPane.showMessageDialog(this, "Invalid Username or Password.", "Authentication Failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private UserAccount authenticate(String username, String password) {
        for(UserAccount ua: this.accountDirectory.getUserAccountList()) {
            if (ua.getUsername().equals(username) && ua.getPassword().equals(password)) {
                return ua;
            }
        }
        return null;
    }


    /**
     * Called by Login action. Switches the main view to the appropriate dashboard.
     */
    public void showDashboard(UserAccount userAccount) {
        String ua = userAccount.getProfile().getRole();
        
        ProfileEnum profile = ProfileEnum.fromProfile(ua); 
        
        switch (profile) {
            case ADMIN:
                adminDashboardPanel = new AdminDashboardJPanel(this, accountDirectory, userAccount);
                workArea.add("AdminDashBoardPanel", adminDashboardPanel);
                CardLayout cardLayout = (CardLayout) workArea.getLayout();
                cardLayout.next(this.workArea);
                break;
            case REGISTRAR:
//                if (registrarDashboardPanel == null) {
//                    registrarDashboardPanel = new RegistrarDashboardJPanel(this, (Registrar) userAccount.getPerson());
//                    mainContentPanel.add(registrarDashboardPanel, "REGISTRAR_DASH");
//                }
//                cardLayout.show(mainContentPanel, "REGISTRAR_DASH");
                break;
            case FACULTY: 
                facultyDashboardPanel = new FacultyDashboardJPanel(this, accountDirectory, userAccount);
                workArea.add("FacultyDashboardPanel", facultyDashboardPanel);
                cardLayout = (CardLayout) workArea.getLayout();
                cardLayout.next(this.workArea);
                
                break;
            default:break;
        }
    }
    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
